---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, system manager, unsupported features 
summary: 已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。 
---
= 已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。



== 與 ASA R2 系統相關的限制

* 在私有模式中使用 BlueXP  時、不支援探索 ASA R2 系統。
* 當您發現 NetApp ASA R2 系統並開啟工作環境之後、系統管理員就會直接將您帶到系統管理員。
+
ASA R2 系統沒有其他管理選項可用。您無法使用標準檢視、也無法啟用 BlueXP 服務。



https://docs.netapp.com/us-en/asa-r2/index.html["深入瞭解 ASA R2 系統"^]



== 不支援的叢集

BlueXP 不支援使用 SAML 驗證設定的內部部署 ONTAP 叢集。



== System Manager 限制

BlueXP 不支援下列 System Manager 功能：

* 叢集設定
+
在內部部署 ONTAP 叢集上設定管理 IP 位址和管理密碼之後、您就可以在 BlueXP 中探索叢集。

* 角色型存取控制（僅限連接器）
+
在使用ONTAP Connector探索及管理內部環境的叢集時、不支援System Manager的角色型存取控制。系統會在探索過程中提示您輸入管理員認證資料。這些認證資料會用於從System Manager採取的所有行動。

+
有了直接探索選項、ONTAP 每次開啟工作環境時、系統都會提示您使用您的憑據登入。

* BlueXP 備份與還原（ Cloud Backup ）啟動
+
叢集版本必須為 9.13.1 、才能從 System Manager 啟用 BlueXP 備份與還原。

+
如果您未使用 Connector 探索叢集、則無法使用 System Manager （進階檢視）來啟用備份與還原。不過、您可以直接從 BlueXP 在內部部署叢集上啟用備份與還原。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["瞭解如何開始使用"^]

* 隨需升級
+
如果叢集版本為 ONTAP 9.9.1 或更新版本、則無法隨需升級韌體和軟體。

+
如果您沒有連接器、則無法從本機機器進行更新、只能從使用 BlueXP 存取的伺服器進行更新。

* 全域搜尋
* 使用者介面設定

