---
sidebar: sidebar 
permalink: task-discovering-ontap.html 
keywords: ontap, cluster, discover, manage, discovering, fas, aff, discover onprem, discover aff cluster, discover cluster, add cluster, active iq, digital wallet 
summary: 探索ONTAP 來自BlueXP的內部資源介紹叢集、以便您開始使用ONTAP 從BlueXP取得的功能完善的系統管理程式來管理磁碟區和執行進階管理。 
---
= 探索內部部署ONTAP 的叢集
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
探索 BlueXP 的內部部署 ONTAP 叢集、以便開始使用 BlueXP 提供的 ONTAP 系統管理員來管理磁碟區和執行進階管理。



== 探索與管理選項

BlueXP提供兩種方法來探索及管理內部ONTAP 的支援功能

透過連接器探索:: 此選項可讓您ONTAP 使用下列功能來管理執行支援功能的叢集：
+
--
* 標準檢視、提供基本的Volume作業
* 進階檢視、可透過System Manager進行管理（ONTAP 支援使用支援的版本為0。9.10.0及更新版本）
* 與 BlueXP 服務整合、提供資料複寫、備份與還原、資料分類及資料分層


此選項需要連接器、您可以將其安裝在雲端供應商或內部部署環境中。

--
直接探索:: 此選項可讓您ONTAP 使用System Manager來管理執行《支援使用程式》9.12.1及更新版本的叢集。沒有其他管理選項可供使用。您無法使用「標準」檢視、也無法啟用資料服務。
+
--
此選項不需要連接器。

當您在執行ONTAP 9.12.1或更新版本的內部部署功能叢集上存取System Manager並連線至BlueXP服務時、系統會提示您直接從BlueXP管理叢集。如果您遵循此提示、它會使用直接探索選項在BluXP中探索叢集。

--


一旦發現、您的叢集就能在BlueXP畫版上做為工作環境使用。

如果您決定稍後再使用其他探索選項、則需要在畫版上將內部叢集探索為獨立的工作環境。然後您可以選擇移除其他工作環境。



== 需求

在您探索內部ONTAP 的功能完善的叢集之前、請先確認您已符合下列要求。



=== 一般要求

* 您應該已經開始使用BlueXP、其中包括登入及設定帳戶。
+
https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["瞭解如何開始使用BlueXP"^]

* 您需要叢集管理IP位址和管理員使用者帳戶的密碼。
* BlueXP會使用ONTAP HTTPS探索叢集。如果您使用自訂防火牆原則、ONTAP 則無法透過連接埠443存取傳入HTTPS。
+
預設的「管理」防火牆原則允許從所有 IP 位址進行傳入 HTTPS 存取。如果您修改此預設原則、或是建立自己的防火牆原則、則必須將 HTTPS 傳輸協定與該原則建立關聯、並啟用從 Connector 主機存取。





=== Connector探索與管理需求

* 內部部署叢集必須執行ONTAP 不含更新版本的功能。
* 連接器必須安裝在雲端供應商或內部部署環境中。
+
如果您想要將冷資料分層至雲端、則應根據您計畫將冷資料分層的位置來審查 Connector 的需求。

+
** https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["深入瞭解連接器"^]
** https://docs.netapp.com/us-en/bluexp-setup-admin/task-managing-connectors.html["在連接器之間切換"^]
** https://docs.netapp.com/us-en/bluexp-tiering/concept-cloud-tiering.html["瞭解 BlueXP 分層"^]


* 連接器主機必須允許透過連接埠 443 進行傳出 HTTPS 存取。
+
如果 Connector 位於雲端、則預先定義的安全性群組會允許所有傳出通訊。





=== 直接探索與管理的需求

* 內部部署叢集必須執行ONTAP 不含更新版本的功能。
* 叢集必須具有與BlueXP服務的傳入和傳出連線：
+
\https://cloudmanager.cloud.netapp.com/ontap-service/check-service-connection

* 您用來存取BlueXP主控台的電腦必須有連至內部ONTAP 叢集的網路連線、這與您提供連線至私有網路中其他資源的方式類似。




== 探索叢集

在ONTAP BlueXP中探索畫版上的內部資料叢集。當您開始探索程序時、BlueXP會探索叢集、如下所示：

* 如果您的活動連接器已連線ONTAP 至您的叢集、則BlueXP會使用該連接器來探索及管理叢集。
* 如果您沒有連接器、或是連接器沒有連線到ONTAP 該叢集、則BlueXP會自動使用「直接探索與管理」選項。


.步驟
. 從導覽功能表中、選取*儲存設備> Canvas*。
. 在「畫版」頁面上、按一下「*新增工作環境*」、然後選取「*內部部署*」。
. 在內部部署ONTAP 的不二字旁、選取* Discover（探索）*。
. 在「_Discover」頁面上、輸入叢集管理IP位址、以及管理使用者帳戶的密碼。
. 如果您直接探索叢集（沒有連接器）、可以選取*儲存認證*。
+
如果您選取此選項、則每次開啟工作環境時、都不需要重新輸入認證資料。這些認證資料僅與您的BlueXP使用者相關聯。您帳戶中的任何人都不會儲存這些檔案以供使用。

. 選擇* Discover（探索）*。
+
如果您沒有 Connector 、而且無法從 BlueXP 存取 IP 位址、系統會提示您建立 Connector 。



.結果
BlueXP會探索叢集、並將其新增為畫版上的工作環境。您現在可以開始管理叢集。

* link:task-manage-ontap-direct.html["瞭解如何直接管理探索到的叢集"]
* link:task-manage-ontap-connector.html["瞭解如何管理透過Connector探索到的叢集"]

